const sampleBuilds=[
{id:"j68",name:"Ultimate 6'8 Two-Way",owner:"Jackie",season:"2K26",position:"SF",height:"6'8\"",weight:"225 lbs",archetype:"Two-Way Inside-Out Scorer",playstyle:"Rec",three:90,dunk:93,standing:90,pass:82,certified:true,status:"approved",featured:true,jumpshot:"Pippen / Ryan / West — 72/28",strengths:"Elite finishing, switchable defense, reliable shooting.",weaknesses:"Would add more rebounding next time.",image:""},
{id:"j69",name:"6'9 Power Forward",owner:"Jackie",season:"2K26",position:"PF",height:"6'9\"",weight:"235 lbs",archetype:"Versatile Two-Way",playstyle:"Rec",three:87,dunk:89,standing:90,pass:82,certified:true,status:"approved",featured:true,jumpshot:"Pippen / Durant / Porter — 60/40",strengths:"Balanced scoring and defense.",weaknesses:"Could use more perimeter defense.",image:""},
{id:"j70",name:"7'0 Stretch Big",owner:"Jackie",season:"2K26",position:"C",height:"7'0\"",weight:"245 lbs",archetype:"Two-Way Stretch Five",playstyle:"Rec",three:90,dunk:80,standing:95,pass:82,certified:true,status:"approved",featured:true,jumpshot:"PJ Washington-style fast release",strengths:"Floor spacing, standing dunk, rim protection.",weaknesses:"Not built for dribbling.",image:""}
];
const jumpshots=[
{name:"6'5–6'9 Smooth Rec",base:"Scottie Pippen",r1:"Ryan",r2:"David West",blend:"72 / 28",speed:"Fast",note:"Jackie's 6'5 SF"},
{name:"6'9 PF Catch & Shoot",base:"Scottie Pippen",r1:"Kevin Durant",r2:"Michael Porter Jr.",blend:"60 / 40",speed:"Fast",note:"Jackie's 6'9 PF"},
{name:"7'0 Stretch Big",base:"PJ Washington",r1:"Custom",r2:"Custom",blend:"Personal timing",speed:"Fast",note:"90 3PT big"}
];
const animations=[
{category:"Motion & Dribble",items:["Kevin Durant motion style","LeBron James pass style","Kobe Bryant triple threat"]},
{category:"Dunk Packages",items:["Two-foot packages first","Quick Drops","Russell Westbrook","Jalen Green","Jaylen Brown"]},
{category:"Big Finishing",items:["Standing dunk 90+ target","Contact standing dunks","Safe reverses","No unnecessary back scratchers"]},
{category:"Build Rules",items:["Pass accuracy 82+","Driving dunk 89–93","Standing dunk 90+","No close-shot-heavy build"]}
];
const players={"2s Players":[["Dab","Coach"],["Mike","Trusted teammate"],["Quan","Shooters shoot"]],"Rec Players":[["Florida","Approved"],["Ball Out","Approved"],["Green Magic","Approved"]],"Crew":[["Chucky","Crew"],["Dman","Crew"],["Smaki","Crew"]],"Friends":[["TTTv","Friend"],["Diff","Friend"],["Pappa Dot","Friend"]]};
const LS={builds:"vault_builds_full",challenges:"vault_challenges_full",user:"vault_user_full"};
let builds=load(LS.builds,sampleBuilds),challenges=load(LS.challenges,[]),currentUser=load(LS.user,null),firebaseMode=false,fb={},authMode="signin";
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}function save(){localStorage.setItem(LS.builds,JSON.stringify(builds));localStorage.setItem(LS.challenges,JSON.stringify(challenges))}
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(m){const t=document.querySelector("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2400)}
function isAdmin(){return currentUser?.email?.toLowerCase()===(window.VAULT_ADMIN_EMAIL||"").toLowerCase()}
async function initFirebase(){const c=window.VAULT_FIREBASE_CONFIG||{};if(!c.apiKey||!c.appId||!c.projectId)return setConnection(false);try{const a=await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js"),u=await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js"),f=await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js");const app=a.initializeApp(c);fb={...u,...f,auth:u.getAuth(app),db:f.getFirestore(app)};firebaseMode=true;setConnection(true);u.onAuthStateChanged(fb.auth,async x=>{currentUser=x?{uid:x.uid,email:x.email}:null;currentUser?localStorage.setItem(LS.user,JSON.stringify(currentUser)):localStorage.removeItem(LS.user);updateAuth();await sync();render()})}catch(e){console.error(e);setConnection(false)}}
function setConnection(on){const b=document.querySelector("#connectionBadge");b.textContent=on?"Firebase connected":"Local mode";b.className="badge "+(on?"online":"local");document.querySelector("#adminMode").textContent=on?"FIREBASE":"LOCAL"}
async function sync(){if(!firebaseMode)return;try{const s=await fb.getDocs(fb.collection(fb.db,"builds"));const r=s.docs.map(d=>({id:d.id,...d.data()}));if(r.length)builds=r;const c=await fb.getDocs(fb.collection(fb.db,"challenges"));challenges=c.docs.map(d=>({id:d.id,...d.data()}));save()}catch(e){console.warn(e)}}
async function addRec(col,data){if(firebaseMode){const r=await fb.addDoc(fb.collection(fb.db,col),{...data,createdAt:fb.serverTimestamp()});return r.id}return crypto.randomUUID()}
async function updateBuild(id,p){builds=builds.map(b=>b.id===id?{...b,...p}:b);save();if(firebaseMode)await fb.updateDoc(fb.doc(fb.db,"builds",id),p)}
async function deleteBuild(id){builds=builds.filter(b=>b.id!==id);save();if(firebaseMode)await fb.deleteDoc(fb.doc(fb.db,"builds",id))}
function go(p){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id==="page-"+p));document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));document.querySelector("#sidebar").classList.remove("open");scrollTo({top:0,behavior:"smooth"})}
function empty(t){return `<div class="panel"><b>${esc(t)}</b></div>`}
function card(b){const bg=b.image?`style="background-image:linear-gradient(rgba(20,5,30,.25),rgba(20,5,30,.25)),url('${esc(b.image)}')"`:"";return `<article class="build-card"><div class="build-image" ${bg}>${b.image?"":"🏀"}${b.certified?'<span class="certified">🏅 JACKIE’S CERTIFIED</span>':""}<span class="season">${esc(b.season||"2K27")}</span></div><div class="build-body"><h3>${esc(b.name)}</h3><div class="meta">${esc(b.owner)} • ${esc(b.position)} • ${esc(b.height)} • ${esc(b.archetype||"")}</div><div class="attrs"><span>3PT<b>${b.three||"—"}</b></span><span>DRV DUNK<b>${b.dunk||"—"}</b></span><span>STD DUNK<b>${b.standing||"—"}</b></span><span>PASS<b>${b.pass||"—"}</b></span></div><button class="secondary view-build" data-id="${b.id}">View Build</button></div></article>`}
function renderBuilds(){const approved=builds.filter(b=>b.status==="approved");document.querySelector("#featuredGrid").innerHTML=approved.filter(b=>b.featured||b.certified).slice(0,3).map(card).join("")||empty("No featured builds yet.");filterMine();filterCommunity();document.querySelector("#approvedCount").textContent=approved.length;document.querySelector("#pendingCount").textContent=builds.filter(b=>b.status==="pending").length;const opts=approved.map(b=>`<option value="${b.id}">${esc(b.name)} — ${esc(b.owner)}</option>`).join("");document.querySelector("#compareA").innerHTML=opts;document.querySelector("#compareB").innerHTML=opts;if(approved.length>1)document.querySelector("#compareB").selectedIndex=1}
function filterMine(){const q=document.querySelector("#mySearch").value.toLowerCase(),p=document.querySelector("#myPosition").value,s=document.querySelector("#mySeason").value;const r=builds.filter(b=>b.certified&&(!q||JSON.stringify(b).toLowerCase().includes(q))&&(!p||b.position===p)&&(!s||b.season===s));document.querySelector("#myGrid").innerHTML=r.map(card).join("")||empty("No builds match those filters.")}
function filterCommunity(){const q=document.querySelector("#communitySearch").value.toLowerCase(),p=document.querySelector("#communityPosition").value;const r=builds.filter(b=>b.status==="approved"&&!b.certified&&(!q||JSON.stringify(b).toLowerCase().includes(q))&&(!p||b.position===p));document.querySelector("#communityGrid").innerHTML=r.map(card).join("")||empty("No approved community builds yet.")}
function showBuild(id){const b=builds.find(x=>x.id===id);if(!b)return;const bg=b.image?`style="background-image:linear-gradient(rgba(20,5,30,.25),rgba(20,5,30,.25)),url('${esc(b.image)}')"`:"";document.querySelector("#buildDetail").innerHTML=`<div class="detail-hero" ${bg}>${b.image?"":"🏀"}</div><span class="eyebrow">${esc(b.season)} • ${esc(b.owner)}</span><h2>${esc(b.name)}</h2><p>${esc(b.position)} • ${esc(b.height)} • ${esc(b.weight||"")} • ${esc(b.archetype||"")}</p><div class="detail-grid"><div>3PT<b>${b.three||"—"}</b></div><div>Driving Dunk<b>${b.dunk||"—"}</b></div><div>Standing Dunk<b>${b.standing||"—"}</b></div><div>Pass Accuracy<b>${b.pass||"—"}</b></div></div><h3>Jump Shot</h3><p>${esc(b.jumpshot||"Not added yet.")}</p><h3>Strengths</h3><p>${esc(b.strengths||"Not added yet.")}</p><h3>Weaknesses / Changes</h3><p>${esc(b.weaknesses||"Not added yet.")}</p>`;document.querySelector("#buildDialog").showModal()}
function renderLibraries(){document.querySelector("#jumpshotGrid").innerHTML=jumpshots.map(j=>`<article class="library-card"><span class="eyebrow">${esc(j.note)}</span><h3>${esc(j.name)}</h3><ul><li><b>Base:</b> ${esc(j.base)}</li><li><b>Release 1:</b> ${esc(j.r1)}</li><li><b>Release 2:</b> ${esc(j.r2)}</li><li><b>Blend:</b> ${esc(j.blend)}</li><li><b>Speed:</b> ${esc(j.speed)}</li></ul></article>`).join("");document.querySelector("#animationGrid").innerHTML=animations.map(a=>`<article class="library-card"><span class="eyebrow">Jackie's Notes</span><h3>${esc(a.category)}</h3><div class="tags">${a.items.map(i=>`<span>${esc(i)}</span>`).join("")}</div></article>`).join("")}
function renderPlayers(){document.querySelector("#playersGrid").innerHTML=Object.entries(players).map(([g,ps])=>`<section class="player-column"><h3>${esc(g)}</h3>${ps.map(p=>`<div class="player-row"><b>${esc(p[0])}</b><small>${esc(p[1])}</small></div>`).join("")}</section>`).join("")}
function renderChallenges(){document.querySelector("#challengeList").innerHTML=challenges.map(c=>`<article class="queue"><div><b>${esc(c.challenger)} vs ${esc(c.opponent)}</b><div class="meta">${esc(c.mode)} • ${new Date(c.date).toLocaleString()}</div></div><span class="ghost">${esc(c.status||"Pending")}</span></article>`).join("")||empty("No squad challenges yet.")}
function renderAdmin(){const p=builds.filter(b=>b.status==="pending");document.querySelector("#adminPending").textContent=p.length;document.querySelector("#adminApproved").textContent=builds.filter(b=>b.status==="approved").length;document.querySelector("#adminChallenges").textContent=challenges.length;document.querySelector("#adminQueue").innerHTML=p.map(b=>`<article class="queue"><div><b>${esc(b.name)}</b><div class="meta">${esc(b.owner)} • ${esc(b.position)} • ${esc(b.height)}</div></div><div class="queue-actions"><button class="secondary view-build" data-id="${b.id}">View</button><button class="approve approve-build" data-id="${b.id}">Approve</button><button class="danger reject-build" data-id="${b.id}">Reject</button></div></article>`).join("")||empty("Nothing is waiting for approval.")}
function updateAuth(){const b=document.querySelector("#authButton");b.textContent=currentUser?`Sign Out (${currentUser.email})`:"Sign In";document.querySelectorAll(".admin-only").forEach(x=>x.classList.toggle("hidden",!isAdmin()));if(!isAdmin()&&document.querySelector("#page-admin").classList.contains("active"))go("home")}
function render(){renderBuilds();renderLibraries();renderPlayers();renderChallenges();renderAdmin();updateAuth()}
async function submitBuild(form){const d=Object.fromEntries(new FormData(form).entries());["three","dunk","standing","pass"].forEach(k=>d[k]=d[k]?Number(d[k]):null);d.status=isAdmin()?"approved":"pending";d.certified=isAdmin();d.featured=false;d.submittedBy=currentUser?.email||"Guest";d.id=await addRec("builds",d);builds.push(d);save();form.reset();render();go(d.status==="approved"?"my-builds":"community");toast(d.status==="approved"?"Build added.":"Build sent for approval.")}
async function authSubmit(e){e.preventDefault();const email=document.querySelector("#authEmail").value.trim(),password=document.querySelector("#authPassword").value,msg=document.querySelector("#authMessage");msg.textContent="";try{if(firebaseMode){authMode==="signin"?await fb.signInWithEmailAndPassword(fb.auth,email,password):await fb.createUserWithEmailAndPassword(fb.auth,email,password)}else{currentUser={uid:"local-"+Date.now(),email};localStorage.setItem(LS.user,JSON.stringify(currentUser));updateAuth()}document.querySelector("#authDialog").close();toast(authMode==="signin"?"Signed in.":"Account created.")}catch(e){msg.textContent=e.message.replace("Firebase: ","")}}
document.addEventListener("click",async e=>{const p=e.target.closest("[data-page]")?.dataset.page;if(p)go(p);const v=e.target.closest(".view-build");if(v)showBuild(v.dataset.id);if(e.target.matches(".approve-build")){await updateBuild(e.target.dataset.id,{status:"approved"});render();toast("Build approved.")}if(e.target.matches(".reject-build")){await deleteBuild(e.target.dataset.id);render();toast("Build rejected.")}});
document.querySelector("#menuButton").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");
document.querySelector("#authButton").onclick=()=>{if(currentUser){if(firebaseMode)fb.signOut(fb.auth);else{currentUser=null;localStorage.removeItem(LS.user);updateAuth();toast("Signed out.")}}else document.querySelector("#authDialog").showModal()};
document.querySelector("#closeAuth").onclick=()=>document.querySelector("#authDialog").close();document.querySelector("#closeBuild").onclick=()=>document.querySelector("#buildDialog").close();document.querySelector("#authForm").onsubmit=authSubmit;
document.querySelector("#authSwitch").onclick=()=>{authMode=authMode==="signin"?"signup":"signin";document.querySelector("#authTitle").textContent=authMode==="signin"?"Sign In":"Create Account";document.querySelector("#authSubmit").textContent=authMode==="signin"?"Sign In":"Create Account";document.querySelector("#authSwitch").textContent=authMode==="signin"?"Need an account? Create one":"Already have an account? Sign in"};
document.querySelector("#buildForm").onsubmit=e=>{e.preventDefault();submitBuild(e.target)};document.querySelector("#mySearch").oninput=filterMine;document.querySelector("#myPosition").onchange=filterMine;document.querySelector("#mySeason").onchange=filterMine;document.querySelector("#communitySearch").oninput=filterCommunity;document.querySelector("#communityPosition").onchange=filterCommunity;
document.querySelector("#seasonButton").onclick=()=>{document.querySelector("#mySeason").value="2K26";go("my-builds");filterMine()};
document.querySelector("#challengeForm").onsubmit=async e=>{e.preventDefault();const c=Object.fromEntries(new FormData(e.target).entries());c.status="Pending";c.id=await addRec("challenges",c);challenges.push(c);save();e.target.reset();renderChallenges();toast("Challenge submitted.")};
document.querySelector("#wizardForm").onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target).entries());let p=builds.filter(b=>b.status==="approved");if(f.role==="guard")p=p.filter(b=>["PG","SG"].includes(b.position));if(f.role==="wing")p=p.filter(b=>["SF","PF"].includes(b.position));if(f.role==="big")p=p.filter(b=>["PF","C"].includes(b.position));if(f.passing==="high")p=p.filter(b=>(b.pass||0)>=82);const score=b=>f.priority==="shooting"?(b.three||0):f.priority==="slashing"?Math.max(b.dunk||0,b.standing||0):f.priority==="defense"?(b.certified?95:70):((b.three||0)+(b.dunk||0)+(b.pass||0))/3;p.sort((a,b)=>score(b)-score(a));const pick=p[0]||builds.find(b=>b.status==="approved"),r=document.querySelector("#wizardResult");r.classList.remove("hidden");r.innerHTML=pick?`<span class="eyebrow">Jackie's Recommendation</span><h2>${esc(pick.name)}</h2><p>${esc(pick.position)} • ${esc(pick.height)} • ${esc(pick.archetype)}</p><button class="primary view-build" data-id="${pick.id}">View Build</button>`:"<b>Add an approved build first.</b>"};
document.querySelector("#compareButton").onclick=()=>{const a=builds.find(b=>b.id===document.querySelector("#compareA").value),b=builds.find(b=>b.id===document.querySelector("#compareB").value);if(!a||!b)return;const fs=[["3PT","three"],["Driving Dunk","dunk"],["Standing Dunk","standing"],["Pass Accuracy","pass"]],one=x=>`<article class="compare-card"><span class="eyebrow">${esc(x.owner)}</span><h2>${esc(x.name)}</h2>${fs.map(([l,k])=>`<div class="compare-line"><span>${l}</span><b class="${(x[k]||0)>((x===a?b:a)[k]||0)?"winner":""}">${x[k]||"—"}</b></div>`).join("")}<p><b>Strengths:</b> ${esc(x.strengths||"—")}</p></article>`;document.querySelector("#comparisonGrid").innerHTML=one(a)+one(b)};
render();initFirebase();
