
const initialBuilds=[
{id:"b1",name:"Ultimate 6'8 Two-Way",owner:"Jackie",season:"2K26",position:"SF",height:"6'8\"",weight:"225 lbs",archetype:"Two-Way Inside-Out Scorer",three:90,dunk:93,standing:90,pass:82,overall:99,jumpshot:"Pippen / Ryan / West — 72/28",strengths:"Elite finishing, switchable defense, reliable shooting.",weaknesses:"Would add more rebounding.",certified:true,status:"approved",image:""},
{id:"b2",name:"6'9 Power Forward",owner:"Jackie",season:"2K26",position:"PF",height:"6'9\"",weight:"235 lbs",archetype:"Versatile Two-Way",three:87,dunk:89,standing:90,pass:82,overall:99,jumpshot:"Pippen / Durant / Porter — 60/40",strengths:"Balanced offense and defense.",weaknesses:"Could use more perimeter defense.",certified:true,status:"approved",image:""},
{id:"b3",name:"7'0 Stretch Big",owner:"Jackie",season:"2K26",position:"C",height:"7'0\"",weight:"245 lbs",archetype:"Two-Way Stretch Five",three:90,dunk:80,standing:95,pass:82,overall:99,jumpshot:"PJ Washington-style fast release",strengths:"Floor spacing, standing dunk, rim protection.",weaknesses:"Not built for dribbling.",certified:true,status:"approved",image:""}
];
const jumpShots=[
{name:"6'5–6'9 Smooth Rec",base:"Scottie Pippen",r1:"Ryan",r2:"David West",blend:"72 / 28",speed:"Fast"},
{name:"6'9 PF Catch & Shoot",base:"Scottie Pippen",r1:"Kevin Durant",r2:"Michael Porter Jr.",blend:"60 / 40",speed:"Fast"},
{name:"7'0 Stretch Big",base:"PJ Washington",r1:"Custom",r2:"Custom",blend:"Personal timing",speed:"Fast"}
];
const animations=[
{name:"Motion & Dribble",items:["Kevin Durant motion style","LeBron James pass style","Kobe Bryant triple threat"]},
{name:"Dunk Packages",items:["Two-foot packages first","Quick Drops","Russell Westbrook","Jalen Green"]},
{name:"Build Rules",items:["Pass accuracy 82+","Driving dunk 89–93","Standing dunk 90+","No close-shot-heavy build"]}
];
const LS={builds:"binder_builds_v1",user:"binder_user_v1"};
let builds=JSON.parse(localStorage.getItem(LS.builds)||"null")||initialBuilds;
let currentUser=JSON.parse(localStorage.getItem(LS.user)||"null");
let firebaseMode=false,fb={},authMode="signin";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const save=()=>localStorage.setItem(LS.builds,JSON.stringify(builds));
const isAdmin=()=>currentUser?.email?.toLowerCase()===(window.VAULT_ADMIN_EMAIL||"").toLowerCase();
function toast(t){const x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2400)}
function go(page){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id==="page-"+page));scrollTo({top:0,behavior:"smooth"})}
function spread(b){const bg=b.image?`style="background-image:linear-gradient(rgba(15,4,25,.25),rgba(15,4,25,.25)),url('${esc(b.image)}')"`:"";return `<article class="build-spread">
<div class="build-left"><div class="build-image" ${bg}>${b.image?"":"🏀"}${b.certified?'<span class="certified">🏅 JACKIE’S CERTIFIED</span>':""}<span class="overall">${b.overall||99}</span></div><div class="build-title"><h3>${esc(b.name)}</h3><p>${esc(b.position)} • ${esc(b.height)} • ${esc(b.weight)} • ${esc(b.archetype)}</p></div></div>
<div class="build-right"><div class="build-header"><div><span class="eyebrow">${esc(b.owner)}</span><h4>${esc(b.name)}</h4></div><span class="season-tag">${esc(b.season)}</span></div>
<div class="attr-grid"><div><span>3PT</span><b>${b.three||"—"}</b></div><div><span>DRIVING DUNK</span><b>${b.dunk||"—"}</b></div><div><span>STANDING DUNK</span><b>${b.standing||"—"}</b></div><div><span>PASS</span><b>${b.pass||"—"}</b></div></div>
<div class="notes"><div class="note-card"><h5>JUMP SHOT</h5><p>${esc(b.jumpshot||"Not added yet.")}</p></div><div class="note-card"><h5>STRENGTHS</h5><p>${esc(b.strengths||"Not added yet.")}</p></div><div class="note-card"><h5>WEAKNESSES</h5><p>${esc(b.weaknesses||"Not added yet.")}</p></div><div class="note-card"><h5>REC NOTES</h5><p>Stats and shooting percentages can be added here.</p></div></div>
<div class="build-actions"><button class="primary view-build" data-id="${b.id}">VIEW FULL BUILD</button></div></div></article>`}
function renderBuilds(){const season=document.querySelector("#seasonFilter")?.value||"",position=document.querySelector("#positionFilter")?.value||"";const mine=builds.filter(b=>b.certified&&(!season||b.season===season)&&(!position||b.position===position));document.querySelector("#buildBinder").innerHTML=mine.map(spread).join("")||"<div class='community-card'>No builds match.</div>";const community=builds.filter(b=>!b.certified&&b.status==="approved");document.querySelector("#communityGrid").innerHTML=community.map(b=>`<article class="community-card"><div class="mini">🏀</div><span class="eyebrow">${esc(b.season)}</span><h3>${esc(b.name)}</h3><p class="meta">${esc(b.owner)} • ${esc(b.position)} • ${esc(b.height)}</p><button class="secondary view-build" data-id="${b.id}">VIEW</button></article>`).join("")||"<div class='community-card'>No approved community builds yet.</div>";document.querySelector("#certifiedCount").textContent=builds.filter(b=>b.certified).length;document.querySelector("#pendingCount").textContent=builds.filter(b=>b.status==="pending").length}
function renderLibraries(){document.querySelector("#jumpShotCards").innerHTML=jumpShots.map(j=>`<article class="library-card"><span class="eyebrow">JACKIE'S RECIPE</span><h3>${esc(j.name)}</h3><p><b>Base:</b> ${esc(j.base)}</p><p><b>Release 1:</b> ${esc(j.r1)}</p><p><b>Release 2:</b> ${esc(j.r2)}</p><p><b>Blend:</b> ${esc(j.blend)}</p><p><b>Speed:</b> ${esc(j.speed)}</p></article>`).join("");document.querySelector("#animationCards").innerHTML=animations.map(a=>`<article class="library-card"><span class="eyebrow">ANIMATION NOTES</span><h3>${esc(a.name)}</h3>${a.items.map(i=>`<p>• ${esc(i)}</p>`).join("")}</article>`).join("")}
function renderAdmin(){const p=builds.filter(b=>b.status==="pending");document.querySelector("#adminQueue").innerHTML=p.map(b=>`<article class="admin-row"><div><b>${esc(b.name)}</b><div class="meta">${esc(b.owner)} • ${esc(b.position)} • ${esc(b.height)}</div></div><div class="admin-actions"><button class="approve" data-approve="${b.id}">APPROVE</button><button class="reject" data-reject="${b.id}">REJECT</button></div></article>`).join("")||"<div class='community-card'>Nothing is waiting for approval.</div>"}
function updateAuth(){document.querySelector("#authButton").textContent=currentUser?`Sign Out (${currentUser.email})`:"Sign In";let admin=document.querySelector('[data-page="admin"]');if(admin)admin.style.display=isAdmin()?"inline-block":"none"}
function render(){renderBuilds();renderLibraries();renderAdmin();updateAuth()}
function showBuild(id){const b=builds.find(x=>x.id===id);if(!b)return;document.querySelector("#buildDetail").innerHTML=`<span class="eyebrow">${esc(b.season)} • ${esc(b.owner)}</span><h2>${esc(b.name)}</h2><p>${esc(b.position)} • ${esc(b.height)} • ${esc(b.weight)} • ${esc(b.archetype)}</p><div class="detail-grid"><div>3PT<br><b>${b.three||"—"}</b></div><div>Driving Dunk<br><b>${b.dunk||"—"}</b></div><div>Standing Dunk<br><b>${b.standing||"—"}</b></div><div>Pass<br><b>${b.pass||"—"}</b></div></div><h3>Jump Shot</h3><p>${esc(b.jumpshot||"Not added.")}</p><h3>Strengths</h3><p>${esc(b.strengths||"Not added.")}</p><h3>Weaknesses</h3><p>${esc(b.weaknesses||"Not added.")}</p>`;document.querySelector("#buildDialog").showModal()}
async function initFirebase(){const c=window.VAULT_FIREBASE_CONFIG||{};if(!c.apiKey||!c.appId)return;try{const a=await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js"),u=await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js"),f=await import("https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js");const app=a.initializeApp(c);fb={...u,...f,auth:u.getAuth(app),db:f.getFirestore(app)};firebaseMode=true;u.onAuthStateChanged(fb.auth,x=>{currentUser=x?{uid:x.uid,email:x.email}:null;currentUser?localStorage.setItem(LS.user,JSON.stringify(currentUser)):localStorage.removeItem(LS.user);updateAuth()})}catch(e){console.error(e)}}
document.addEventListener("click",async e=>{const page=e.target.closest("[data-page]")?.dataset.page;if(page)go(page);const v=e.target.closest(".view-build");if(v)showBuild(v.dataset.id);if(e.target.dataset.approve){const id=e.target.dataset.approve;builds=builds.map(b=>b.id===id?{...b,status:"approved"}:b);save();render();toast("Build approved.")}if(e.target.dataset.reject){builds=builds.filter(b=>b.id!==e.target.dataset.reject);save();render();toast("Build rejected.")}});
document.querySelector("#seasonFilter").onchange=renderBuilds;document.querySelector("#positionFilter").onchange=renderBuilds;
document.querySelector("#buildForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());["three","dunk","standing","pass"].forEach(k=>d[k]=d[k]?Number(d[k]):null);d.id=crypto.randomUUID();d.status=isAdmin()?"approved":"pending";d.certified=isAdmin();d.overall=99;builds.push(d);save();render();e.target.reset();go("community");toast(d.status==="approved"?"Build added.":"Build sent for approval.")};
document.querySelector("#authButton").onclick=()=>{if(currentUser){if(firebaseMode)fb.signOut(fb.auth);else{currentUser=null;localStorage.removeItem(LS.user);updateAuth()}}else document.querySelector("#authDialog").showModal()};
document.querySelector("#closeAuth").onclick=()=>document.querySelector("#authDialog").close();document.querySelector("#closeBuild").onclick=()=>document.querySelector("#buildDialog").close();
document.querySelector("#authSwitch").onclick=()=>{authMode=authMode==="signin"?"signup":"signin";document.querySelector("#authTitle").textContent=authMode==="signin"?"Sign In":"Create Account";document.querySelector("#authSubmit").textContent=authMode==="signin"?"SIGN IN":"CREATE ACCOUNT"};
document.querySelector("#authForm").onsubmit=async e=>{e.preventDefault();const email=document.querySelector("#authEmail").value.trim(),password=document.querySelector("#authPassword").value,msg=document.querySelector("#authMessage");msg.textContent="";try{if(firebaseMode){authMode==="signin"?await fb.signInWithEmailAndPassword(fb.auth,email,password):await fb.createUserWithEmailAndPassword(fb.auth,email,password)}else{currentUser={email};localStorage.setItem(LS.user,JSON.stringify(currentUser));updateAuth()}document.querySelector("#authDialog").close()}catch(err){msg.textContent=err.message}};
render();initFirebase();
